[package]
name = "dlb-kmer-sampling"
version = "0.1.0"
edition = "2021"

[dependencies]
wyhash = "0.5.0"
rustc-hash = "1.1"
simulate-seqs = { git = "https://github.com/Daniel-Liu-c0deb0t/simulate-seqs" }
